import { VerticalBox, GridBox, HorizontalBox, TextEdit, Button} from "std-widgets.slint";

export component MainWindow {
    width: 800px;
    height: 800px;
    HorizontalBox {
       
        Rectangle {
            background: blue;
            height: 100%;
            width: 10%;
        }
        VerticalBox {
            width: 100%;
        
                Rectangle {
                    height: 50px;
                    width: 90% ;
                    background: red;
                    Button {
                        text: "File";
                    }
                }
                TextEdit {
                   
                    font-size: 14px;
                }
            }
    }
   
    
}